DROP ТАБLЕ IF EXISTS CONTACT;
CREATE TABLE CONTACT (
  ID INT NOT NULL AUTO INCREMENT
  , FIRST_NAМE VARCHAR(бO) NOT NULL
  , LAST_NAМE VARCНAR(40) NOT NULL
  , BIRTH DATE DATE
  , DESCRIPTION VARCHAR(2000)
  , РНОТО BLOB
  , VERSION INT NOT NULL DEFAULT О
  , UNIQUE UQ_CONTACT_l (FIRST_NAМE, LAST_NAМE)
  , PRIМARY КЕУ (ID)
) ;